CREATE DATABASE tickets;

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    name VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(255) NOT NULL
);

CREATE TABLE tickets (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    status NUMBER NOT NULL, -- TicketStatus as ordinal
    priority NUMBER NOT NULL, -- Priority as ordinal
    category NUMBER NOT NULL, -- Category as ordinal
    created_at TIMESTAMP NOT NULL,
    owner_id NUMBER NOT NULL,
    CONSTRAINT fk_ticket_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE comments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text CLOB NOT NULL,
    ticket_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    CONSTRAINT fk_comment_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),
    CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE ticket_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_status NUMBER NOT NULL, -- TicketStatus as ordinal
    created_at TIMESTAMP NOT NULL,
    ticket_id NUMBER NOT NULL,
    CONSTRAINT fk_ticket_log_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id)
);

CREATE INDEX idx_ticket_owner ON tickets(owner_id);
CREATE INDEX idx_comment_ticket ON comments(ticket_id);
CREATE INDEX idx_ticket_log_ticket ON ticket_logs(ticket_id);
